services:
  ai-stremio-search:
    image: ghcr.io/mkcfdc/aisearch:latest
    container_name: ai-stremio-search
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    command: ["deno", "run", "--allow-net", "--allow-env", "--allow-read=.", "--quiet", "--allow-run=docker,docker-compose", "main.ts"]
    networks:
      - secure_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: always
    networks:
      - secure_net

networks:
  secure_net:
    driver: bridge