services:
  app:
    build: .
    container_name: deno-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    command: ["deno", "run", "--allow-net", "--allow-env", "--allow-read=.", "main.ts"]
    networks:
      - secure_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: always
    networks:
      - secure_net

networks:
  secure_net:
    driver: bridge