name: Docker Build, Push to GHCR, and Deploy via Webhook

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (SHA tag)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false # Don't push yet
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build and Push Docker image (latest and tag if applicable)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('ghcr.io/${{ github.repository }}:{0}', github.ref_name) || '' }} # Tag with the release tag
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Send webhook to trigger deployment
        uses: actions/http-client@v2
        with:
          url: ${{ secrets.VPS_WEBHOOK_URL }}
          method: POST
          headers:
            Content-Type: application/json
            x-webhook-secret: ${{ secrets.WEBHOOK_SECRET }}
          body: |
            {
              "image_tag": "ghcr.io/${{ github.repository }}:latest" # Or use the SHA tag if you prefer
            }